export default [
    {
      id: 1,
      postedOn: new Date(),
      title: "Addfeild",
      type: "Full time",
      location: "Remote",
      companyName: "Amazon",
      companyUrl: "Amazon.com",
      skills: ["Javascript", "React.js", "Node.js"],
      link: "https://www.amazon.jobs/en/",
    },
    {
      id: 2,
      postedOn: new Date(),
      title: "Business Development Associate",
      type: "Part time",
      location: "Office",
      companyName: "Byjus",
      companyUrl: "Byjus.com",
      skills: ["Angular", "Node.js"],
      link: "https://byjus.com/apply/",
    },
    {
      id: 3,
      postedOn: new Date(),
      title: "Customer Support Executive",
      type: "Full time",
      location: "Remote",
      companyName: "Flipkart",
      companyUrl: "https://flipkart.com",
      skills: ["flutter"],
      link: "https://www.flipkartcareers.com/",
    },
    {
      id: 4,
      postedOn: new Date(),
      title: "Voice process",
      type: "Part time",
      location: "Remote",
      companyName: "mPokket",
      companyUrl: "https://mPokket.com",
      skills: ["flutter"],
      link: "https://mpokket.in/careers/",
    },
    {
      id: 5,
      postedOn: new Date(),
      title: "Senior associate-HR",
      type: "Full time",
      location: "Remote",
      companyName: "Sharechat",
      companyUrl: "https://Sharechat.com",
      skills: ["flutter"],
      link: "https://sharechat.com/careers",
    },
  ];